"""Renders COSMOS command and telemetry definition files from an F Prime dictionary

The generated files use `<%= target_name %>` so that COSMOS substitutes the target name chosen at plugin
installation; that is the only ERB in the output and it is resolved by COSMOS itself.
"""

from __future__ import annotations

import re
from collections.abc import Iterable

from fprime_gds.common.templates.ch_template import ChTemplate
from fprime_gds.common.templates.cmd_template import CmdTemplate
from fprime_gds.common.templates.pkt_template import PktTemplate

from fprime_openc3.dictionary import TIME_SECONDS_BITS, TIME_USECONDS_BITS, FprimeDictionary, WireLayout
from fprime_openc3.items import CosmosItem, flatten

TARGET = "<%= target_name %>"
CHANNELIZED_PACKET = "FPRIME_CHANNELS"
UNKNOWN_PACKET = "FPRIME_UNKNOWN"
CHANNELS_BLOCK = "CHANNELS"
DESCRIPTOR_ITEM = "FPRIME_DESCRIPTOR"
OPCODE_ITEM = "FPRIME_OPCODE"
CHANNEL_ID_ITEM = "FPRIME_CHANNEL_ID"
PACKET_ID_ITEM = "FPRIME_PACKET_ID"
TIME_ITEMS = ("FPRIME_TIME_BASE", "FPRIME_TIME_CONTEXT", "FPRIME_TIME_SECONDS", "FPRIME_TIME_USECONDS")
# Not named PACKET_TIME on purpose: F Prime time is only Unix time for TB_WORKSTATION_TIME, so COSMOS keeps
# stamping packets with the received time and the F Prime time is available as a separate item.
TIME_ITEM = "FPRIME_TIME"
SUBPACKETIZER = "fprime_subpacketizer.py"
TIME_CONVERSION = "openc3/conversions/unix_time_conversion.py"
HEADER = "# Generated by fprime-to-openc3 from {dictionary} ({deployment}). Do not edit.\n"

# Python format specs that translate directly into printf conversions
_FORMAT_SPEC = re.compile(r"\{(?::([^{}]*))?\}")
_PRINTF_CONVERSIONS = set("dioxXeEfFgG")


def quote(text: str | None) -> str:
    """Render text as a COSMOS double-quoted string"""
    cleaned = " ".join((text or "").split()).replace('"', "'").replace("<%", "< %")
    return f'"{cleaned}"'


def printf_format(format_str: str | None) -> str | None:
    """Convert an fprime-gds (Python) format string to a printf-style COSMOS FORMAT_STRING, or None if not needed"""
    if not format_str or format_str == "{}":
        return None
    converted = format_str
    for match in _FORMAT_SPEC.finditer(format_str):
        spec = match.group(1) or ""
        if not spec:
            replacement = "%s"
        elif spec[-1] in _PRINTF_CONVERSIONS and re.fullmatch(r"[-+ 0#]*\d*(?:\.\d+)?[a-zA-Z]", spec):
            replacement = "%" + spec
        else:
            return None
        converted = converted.replace(match.group(0), replacement, 1)
    return converted


def full_name(template: CmdTemplate | ChTemplate | PktTemplate) -> str:
    if isinstance(template, PktTemplate):
        return template.get_name()
    return template.get_full_name()


def _states(item: CosmosItem, indent: str) -> list[str]:
    return [f"{indent}STATE {name} {value}" for name, value in item.states]


def _parameter_lines(item: CosmosItem, id_value: int | None = None) -> list[str]:
    keyword = "APPEND_ID_PARAMETER" if id_value is not None else "APPEND_PARAMETER"
    if item.is_array:
        array = f"{item.name} {item.bit_size} {item.data_type} {item.array_bit_size}"
        lines = [f"  APPEND_ARRAY_PARAMETER {array} {quote(item.description)}"]
    elif item.data_type == "STRING":
        lines = [f'  {keyword} {item.name} {item.bit_size} STRING "" {quote(item.description)}']
    else:
        minimum, maximum = item.value_range()
        default = item.default if id_value is None else id_value
        scalar = f"{item.name} {item.bit_size} {item.data_type} {minimum} {maximum} {default}"
        lines = [f"  {keyword} {scalar} {quote(item.description)}"]
    lines.extend(_states(item, "    "))
    if item.is_variable_string:
        lines.append(f"    VARIABLE_BIT_SIZE {item.length_item} 8 0")
    if item.fprime_type:
        lines.append(f"    META FPRIME_TYPE {quote(item.fprime_type)}")
    return lines


def _item_lines(item: CosmosItem, id_value: int | None = None, extra: Iterable[str] = ()) -> list[str]:
    keyword = "APPEND_ID_ITEM" if id_value is not None else "APPEND_ITEM"
    if item.is_array:
        array = f"{item.name} {item.bit_size} {item.data_type} {item.array_bit_size}"
        lines = [f"  APPEND_ARRAY_ITEM {array} {quote(item.description)}"]
    elif id_value is not None:
        lines = [f"  {keyword} {item.name} {item.bit_size} {item.data_type} {id_value} {quote(item.description)}"]
    else:
        lines = [f"  {keyword} {item.name} {item.bit_size} {item.data_type} {quote(item.description)}"]
    lines.extend(_states(item, "    "))
    if item.is_variable_string:
        lines.append(f"    VARIABLE_BIT_SIZE {item.length_item} 8 0")
    lines.extend(f"    {line}" for line in extra)
    if item.fprime_type:
        lines.append(f"    META FPRIME_TYPE {quote(item.fprime_type)}")
    return lines


def _channel_modifiers(channel: ChTemplate, item: CosmosItem) -> list[str]:
    """FORMAT_STRING and LIMITS modifiers for the scalar item carrying a channel value"""
    modifiers = []
    format_str = printf_format(channel.get_format_str())
    if format_str and item.data_type in ("INT", "UINT", "FLOAT") and not item.states:
        modifiers.append(f"FORMAT_STRING {quote(format_str)}")
    bounds = (channel.get_low_red(), channel.get_low_yellow(), channel.get_high_yellow(), channel.get_high_red())
    if item.data_type in ("INT", "UINT", "FLOAT") and any(bound is not None for bound in bounds):
        if item.data_type == "FLOAT":
            minimum, maximum = "-1e308", "1e308"
        else:
            minimum, maximum = item.value_range()
        red_low, yellow_low, yellow_high, red_high = bounds
        red_low = minimum if red_low is None else red_low
        yellow_low = red_low if yellow_low is None else yellow_low
        red_high = maximum if red_high is None else red_high
        yellow_high = red_high if yellow_high is None else yellow_high
        modifiers.append(f"LIMITS DEFAULT 1 ENABLED {red_low} {yellow_low} {yellow_high} {red_high}")
    return modifiers


def _time_items(layout: WireLayout) -> list[str]:
    base, context, seconds, useconds = TIME_ITEMS
    lines = [f"  APPEND_ITEM {base} {layout.time_base_bits} UINT {quote('F Prime time base')}"]
    lines.extend(f"    STATE {name} {value}" for name, value in layout.time_base_states.items())
    lines.extend(
        [
            f"  APPEND_ITEM {context} {layout.time_context_bits} UINT {quote('F Prime time context')}",
            f"  APPEND_ITEM {seconds} {TIME_SECONDS_BITS} UINT {quote('F Prime time seconds')}",
            f"  APPEND_ITEM {useconds} {TIME_USECONDS_BITS} UINT {quote('F Prime time microseconds')}",
            f"  ITEM {TIME_ITEM} 0 0 DERIVED {quote('F Prime time as Unix time (valid for TB_WORKSTATION_TIME)')}",
            f"    READ_CONVERSION {TIME_CONVERSION} {seconds} {useconds}",
        ]
    )
    return lines


def _value_items(name: str, template: ChTemplate, layout: WireLayout) -> list[str]:
    lines = []
    for item in flatten(name, template.get_type_obj(), layout, template.get_ch_desc() or ""):
        lines.extend(_item_lines(item, extra=_channel_modifiers(template, item)))
    return lines


def emit_command(command: CmdTemplate, layout: WireLayout) -> list[str]:
    lines = [f"COMMAND {TARGET} {full_name(command)} BIG_ENDIAN {quote(command.get_description())}"]
    descriptor = CosmosItem(
        DESCRIPTOR_ITEM,
        layout.descriptor_bits,
        "UINT",
        "F Prime packet descriptor",
        fprime_type="FwPacketDescriptorType",
    )
    opcode = CosmosItem(OPCODE_ITEM, layout.opcode_bits, "UINT", "F Prime command opcode", fprime_type="FwOpcodeType")
    lines.extend(_parameter_lines(descriptor, layout.command_descriptor))
    lines.extend(_parameter_lines(opcode, command.get_op_code()))
    for arg_name, arg_description, arg_type in command.get_args():
        for item in flatten(arg_name, arg_type, layout, arg_description or ""):
            lines.extend(_parameter_lines(item))
    return lines


def emit_commands(dictionary: FprimeDictionary) -> str:
    blocks = [HEADER.format(dictionary=dictionary.path.name, deployment=dictionary.deployment_name)]
    for command in dictionary.commands:
        blocks.append("\n".join(emit_command(command, dictionary.layout)) + "\n")
    return "\n".join(blocks)


def emit_channel(channel: ChTemplate, layout: WireLayout) -> list[str]:
    lines = [f"TELEMETRY {TARGET} {full_name(channel)} BIG_ENDIAN {quote(channel.get_ch_desc())}", "  SUBPACKET"]
    channel_id = CosmosItem(
        CHANNEL_ID_ITEM, layout.channel_id_bits, "UINT", "F Prime channel identifier", fprime_type="FwChanIdType"
    )
    lines.extend(_item_lines(channel_id, channel.get_id()))
    lines.extend(_time_items(layout))
    lines.extend(_value_items(channel.get_name(), channel, layout))
    return lines


def emit_channelized_parent(layout: WireLayout) -> list[str]:
    descriptor = CosmosItem(
        DESCRIPTOR_ITEM,
        layout.descriptor_bits,
        "UINT",
        "F Prime packet descriptor",
        fprime_type="FwPacketDescriptorType",
    )
    description = quote("F Prime channelized telemetry (split into one subpacket per channel)")
    lines = [f"TELEMETRY {TARGET} {CHANNELIZED_PACKET} BIG_ENDIAN {description}", f"  SUBPACKETIZER {SUBPACKETIZER}"]
    lines.extend(_item_lines(descriptor, layout.telemetry_descriptor))
    lines.append(f"  APPEND_ITEM {CHANNELS_BLOCK} 0 BLOCK {quote('Concatenated channel records')}")
    lines.append("    HIDDEN")
    return lines


def emit_unknown_packet(layout: WireLayout) -> list[str]:
    descriptor = CosmosItem(
        DESCRIPTOR_ITEM,
        layout.descriptor_bits,
        "UINT",
        "F Prime packet descriptor",
        fprime_type="FwPacketDescriptorType",
    )
    description = quote("F Prime packets not handled by this plugin (events, files, data products)")
    lines = [f"TELEMETRY {TARGET} {UNKNOWN_PACKET} BIG_ENDIAN {description}", "  CATCHALL"]
    lines.extend(_item_lines(descriptor))
    lines.extend(f"    STATE {name} {value}" for name, value in layout.packet_types.items())
    lines.append(f"  APPEND_ITEM DATA 0 BLOCK {quote('Remaining packet bytes')}")
    return lines


def emit_channels(dictionary: FprimeDictionary) -> str:
    layout = dictionary.layout
    blocks = [HEADER.format(dictionary=dictionary.path.name, deployment=dictionary.deployment_name)]
    blocks.append("\n".join(emit_channelized_parent(layout)) + "\n")
    for channel in dictionary.channels:
        blocks.append("\n".join(emit_channel(channel, layout)) + "\n")
    blocks.append("\n".join(emit_unknown_packet(layout)) + "\n")
    return "\n".join(blocks)


def emit_packet(packet: PktTemplate, layout: WireLayout) -> list[str]:
    description = quote(f"F Prime packetized telemetry {packet.get_name()}")
    lines = [f"TELEMETRY {TARGET} {full_name(packet)} BIG_ENDIAN {description}"]
    descriptor = CosmosItem(
        DESCRIPTOR_ITEM,
        layout.descriptor_bits,
        "UINT",
        "F Prime packet descriptor",
        fprime_type="FwPacketDescriptorType",
    )
    packet_id = CosmosItem(
        PACKET_ID_ITEM, layout.packet_id_bits, "UINT", "F Prime packet identifier", fprime_type="FwTlmPacketizeIdType"
    )
    lines.extend(_item_lines(descriptor, layout.packetized_descriptor))
    lines.extend(_item_lines(packet_id, packet.get_id()))
    lines.extend(_time_items(layout))
    for channel in packet.get_ch_list():
        lines.extend(_value_items(full_name(channel), channel, layout))
    return lines


def emit_packets(dictionary: FprimeDictionary) -> str:
    blocks = [HEADER.format(dictionary=dictionary.path.name, deployment=dictionary.deployment_name)]
    for packet in dictionary.packets:
        blocks.append("\n".join(emit_packet(packet, dictionary.layout)) + "\n")
    return "\n".join(blocks)
