"""Assembles a complete COSMOS plugin directory (and gem) from an F Prime dictionary"""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass
from importlib import resources
from pathlib import Path

from fprime_cosmos import emit
from fprime_cosmos.dictionary import FprimeDictionary
from fprime_cosmos.gem import GemSpec, build_gem

STATIC_PLUGIN = resources.files("fprime_cosmos") / "plugin"
STATIC_TARGET = "FPRIME"
GEM_NAME_PREFIX = "openc3-cosmos-fprime"
COSMOS_MINIMUM_VERSION = "6.10.0"
BASE_VERSION = "1.0.0"


@dataclass(frozen=True)
class PluginArtifacts:
    directory: Path
    gem_name: str
    version: str
    gem_path: Path | None = None

    @property
    def plugin_prefix(self) -> str:
        """Prefix of the COSMOS plugin name, which is `<gem>-<version>__<timestamp>` once installed"""
        return f"{self.gem_name}-{self.version}"


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def gem_name_for(dictionary: FprimeDictionary) -> str:
    return f"{GEM_NAME_PREFIX}-{slug(dictionary.deployment_name.rsplit('.', 1)[-1])}"


def version_for(dictionary: FprimeDictionary) -> str:
    """Gem version carrying the dictionary digest so COSMOS sees a new version whenever the dictionary changes"""
    return f"{BASE_VERSION}.{dictionary.content_hash()}"


def write_plugin(dictionary: FprimeDictionary, output: Path, target_name: str = STATIC_TARGET) -> Path:
    """Write the plugin source tree under output and return the plugin directory"""
    output = Path(output)
    if output.exists():
        shutil.rmtree(output)
    with resources.as_file(STATIC_PLUGIN) as static:
        shutil.copytree(static, output, ignore=shutil.ignore_patterns("__pycache__"))
    if target_name != STATIC_TARGET:
        (output / "targets" / STATIC_TARGET).rename(output / "targets" / target_name)
        plugin_txt = output / "plugin.txt"
        plugin_txt.write_text(plugin_txt.read_text().replace(f"TARGET {STATIC_TARGET} ", f"TARGET {target_name} "))
    cmd_tlm = output / "targets" / target_name / "cmd_tlm"
    cmd_tlm.mkdir()
    (cmd_tlm / "commands.txt").write_text(emit.emit_commands(dictionary))
    (cmd_tlm / "channels.txt").write_text(emit.emit_channels(dictionary))
    if dictionary.packets:
        (cmd_tlm / "packets.txt").write_text(emit.emit_packets(dictionary))
    plugin_txt = output / "plugin.txt"
    plugin_txt.write_text(
        plugin_txt.read_text().replace(
            "VARIABLE fprime_target_name FPRIME", f"VARIABLE fprime_target_name {target_name}"
        )
    )
    return output


def build_plugin(
    dictionary: FprimeDictionary, output: Path, target_name: str = STATIC_TARGET, gem: bool = True
) -> PluginArtifacts:
    """Write the plugin tree to output/<gem name> and, optionally, build output/<gem name>-<version>.gem"""
    output = Path(output)
    gem_name = gem_name_for(dictionary)
    version = version_for(dictionary)
    directory = write_plugin(dictionary, output / gem_name, target_name)
    gem_path = None
    if gem:
        spec = GemSpec(
            name=gem_name,
            version=version,
            summary=f"OpenC3 COSMOS plugin for the F Prime deployment {dictionary.deployment_name}",
            description=f"Generated by fprime-to-cosmos from {dictionary.path.name} ({dictionary.content_hash()})",
            metadata={
                "openc3_cosmos_minimum_version": COSMOS_MINIMUM_VERSION,
                "fprime_dictionary_hash": dictionary.content_hash(),
            },
        )
        gem_path = build_gem(spec, directory, output / f"{gem_name}-{version}.gem")
    return PluginArtifacts(directory=directory, gem_name=gem_name, version=version, gem_path=gem_path)
